// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI_2021.Data;

namespace PI_2021.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210323164712_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "7f62d2ac-781b-483e-b9b8-4d2e3d148a88",
                            ConcurrencyStamp = "a6b534ba-6aa7-4a2b-86dc-6899b80bf947",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1678e85f-dbf8-499a-8ee3-9d1ba87d8e03",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b6f8e03-03ee-4731-9911-d161b35bb974",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEE4jhZijduz6WcIziS40yYByUMECFCOvw131uzXslCAiKyiFsgG9vAsB/ejWbr6Qzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "111e4a54-d769-4ccd-8f9f-17afaba7e508",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "1678e85f-dbf8-499a-8ee3-9d1ba87d8e03",
                            RoleId = "7f62d2ac-781b-483e-b9b8-4d2e3d148a88"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PI_2021.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<char>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 2,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 3,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 4,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 5,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 6,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 7,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 8,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 9,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 10,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 11,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 12,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 13,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 14,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 15,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 16,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 17,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 18,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 19,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 20,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 21,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 22,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 23,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 24,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 25,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 26,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 27,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 28,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 29,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 30,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 31,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 32,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 33,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 34,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        },
                        new
                        {
                            PersonID = 35,
                            Age = 25,
                            City = "Warszawa",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nisl massa, vestibulum euismod magna non, iaculis rutrum quam. Donec eget feugiat libero, vitae consectetur ante. Morbi pretium efficitur felis ac rutrum. Curabitur interdum viverra augue, vitae eleifend lorem tristique sit amet. Donec aliquet pretium magna, fermentum consequat orci consequat nec. Sed a velit non libero mollis vehicula in ac orci. Mauris vel velit finibus, lacinia urna vestibulum, scelerisque elit. Donec at odio ipsum. Maecenas vehicula quam ut leo efficitur, quis ornare tortor posuere. Nam suscipit dapibus pretium.",
                            FirstName = "Imie",
                            Gender = 'K',
                            LastName = "Nazwisko",
                            Picture = "sample.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
